plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'maven-publish'
}

apply from: rootProject.file("../gradle/fabric-common.gradle")

dependencies {
    // MSD FABRIC 1.4.0 for MTR 4.0.0 + 1.20.4
    modImplementation "curse.maven:station-decoration-790307:6893840"
}
